elasticsearch:
  image: elasticsearch:1.7.2
  command: elasticsearch -Des.index.number_of_shards="1" -Des.index.number_of_replicas="0"
api:
  build: .
  ports:
    - '8080'
  links:
    - elasticsearch
dev:
  build: .
  ports:
    - '8080'
  volumes:
    - .:/src
  links:
    - elasticsearch
  command: npm run watch
