swagger: '2.0'

info:
  version: "1.0.0"
  title: Search API
  
basePath: /1

paths:
  /indexes:
    get:
      description: |
        List all `Index` objects.
      responses:
        200:
          description: An array of indexes
          schema:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                  description: Unique index name
                createdAt:
                  type: string
                  description: An ISO 8061 formatted date string for when the index was created
                updatedAt:
                  type: string
                  description: An ISO 8061 formatted date string for when the index was last updated
                entries:
                  type: integer
                  format: int32
                  description: Number of records contained within the index
                pendingTask:
                  type: boolean
                  description: An update task is currently running
                lastBuildTimeS:
                  type: integer
                  format: int32
                  description: Time taken to build the index
                dataSize:
                  type: integer
                  format: int32
                  description: Size of the data held within the index
              
  /indexes/{name}:
    get:
      description: |
        Query an index.
      responses:
        200:
          description: Search results
          schema:
            type: array
            items:
              type: object
    parameters:
      - name: name
        in: path
        description: Name of the index to query
        required: true
        type: string
      - name: query
        in: query
        description: Search keywords
        required: true
        type: string
    
  /indexes/{name}:
    post:
      description: |
        Add an object to the index and automatically assign an identifier.
      responses:
        201:
          description: Indexing task created
          schema:
            $ref: '#/definitions/Task'
    parameters:
      - name: name
        in: path
        description: Name of the index in which to create the object
        required: true
        type: string
        
  /indexes/{name}/{objectID}:
    get:
      description: |
        Retrieve an object from the index by it's identifier.
      responses:
        200:
          description: Object with identifier found
          schema:
            type: object
            description: The object with the given identifier
    parameters:
      - name: name
        in: path
        description: Name of the index to search
        required: true
        type: string
      - name: objectID
        in: path
        description: The identifier of the object to retrieve
        required: true
        type: string
        
  /indexes/{name}/{objectID}:
    put:
      description: |
        Add an object with the identifier, or replace when it already exists
      responses:
        200:
          description: Indexing task created
          schema:
            $ref: '#/definitions/Task'
    parameters:
      - name: name
        in: path
        description: Name of the index to search
        required: true
        type: string
      - name: objectID
        in: path
        description: The identifier of the object to add/replace
        required: true
        type: string
  
  /indexes/{name}/{objectID}:
    delete:
      description: |
        Delete an object by it's identifier.
      responses:
        204:
          description: Object deleted
    parameters:
      - name: name
        in: path
        description: Name of the index to search
        required: true
        type: string
      - name: objectID
        in: path
        description: The identifier of the object to delete
        required: true
        type: string
  
  /indexes/{name}/query:
    post:
      description: |
        Performs a search on an index
      responses:
        200:
          description: Search results
          schema:
            type: array
            items:
              type: object
    parameters:
      - name: name
        in: path
        description: Name of the index to query
        required: true
        type: string
      - name: params
        in: body
        description: The search query
        required: true
        schema:
          type: object
          properties:
            query:
              type: string
              description: Search keywords
      
  /indexes/{indexName}/task/{taskID}:
    get:
      description: |
        Get details of an indexing task.
      responses:
        200:
          description: Task found
          schema:
            type: object
            properties:
              status:
                type: string
                description: The status of the task (published or notPublished)
              pendingTask:
                type: boolean
                description: Indicates whether the index has remaining tasks running
    parameters:
      - name: indexName
        in: path
        description: Name of the index containing the task
        required: true
        type: string
      - name: taskID
        in: path
        description: The identifier of the task
        type: integer
        format: int32
        required: true
    
definitions:
  Task:
    type: object
    properties:
      createdAt:
        type: string
        description: An ISO 8061 formatted date string
      taskID:
        type: integer
        format: int32
        description: Identifier of the indexing task
      objectID:
        type: string
        description: The identifier of the object being indexed