swagger: '2.0'

info:
  version: "1.0.0"
  title: Search API
  
basePath: /1

paths:
  /indexes:
    get:
      description: |
        List all `Index` objects.
      responses:
        200:
          description: An array of indexes
          schema:
            type: array
            items:
              $ref: '#/definitions/Index'
              
  /indexes/{name}:
    get:
      description: |
        Query an index.
      responses:
        200:
          description: Search results
          schema:
            type: array
            items:
              type: object
    parameters:
      - name: name
        in: path
        description: Name of the index to query
        required: true
        type: string
      - name: query
        in: query
        description: Search keywords
        required: true
        type: string
    
  /indexes/{name}:
    post:
      description: |
        Add an object to the index and automatically assign an identifier.
      responses:
        201:
          description: Object created
          schema:
            type: object
            description: The indexed object with an automatically generated identifier
    parameters:
      - name: name
        in: path
        description: Name of the index in which to create the object
        required: true
        type: string
        
  /indexes/{name}/{objectID}:
    get:
      description: |
        Retrieve an object from the index by it's identifier.
      responses:
        200:
          description: Object with identifier found
          schema:
            type: object
            description: The object with the given identifier
    parameters:
      - name: name
        in: path
        description: Name of the index to search
        required: true
        type: string
      - name: objectID
        in: path
        description: The identifier of the object to retrieve
        required: true
        type: string
        
  /indexes/{name}/{objectID}:
    put:
      description: |
        Add an object with the identifier, or replace when it already exists
      responses:
        200:
          description: Object added/replaced
          schema:
            type: object
            description: The object added/replaced
    parameters:
      - name: name
        in: path
        description: Name of the index to search
        required: true
        type: string
      - name: objectID
        in: path
        description: The identifier of the object to add/replace
        required: true
        type: string
  
  /indexes/{name}/{objectID}:
    delete:
      description: |
        Delete an object by it's identifier.
      responses:
        204:
          description: Object deleted
    parameters:
      - name: name
        in: path
        description: Name of the index to search
        required: true
        type: string
      - name: objectID
        in: path
        description: The identifier of the object to delete
        required: true
        type: string
  
  /indexes/{name}/query:
    post:
      description: |
        Performs a search on an index
      responses:
        200:
          description: Search results
          schema:
            type: array
            items:
              type: object
    parameters:
      - name: name
        in: path
        description: Name of the index to query
        required: true
        type: string
      - name: params
        in: body
        description: The search query
        required: true
        schema:
          $ref: '#/definitions/SearchQuery'
      
definitions:
  Index:
   properties:
      name:
        type: string
        description: Unique index name
      createdAt:
        type: string
        description: An ISO 8061 formatted date string for when the index was created
      updatedAt:
        type: string
        description: An ISO 8061 formatted date string for when the index was last updated
      entries:
        type: integer
        format: int32
        description: Number of records contained within the index
      pendingTask:
        type: boolean
        description: An update task is currently running
      lastBuildTimeS:
        type: integer
        format: int32
        description: Time taken to build the index
      dataSize:
        type: integer
        format: int32
        description: Size of the data held within the index
  SearchQuery:
    properties:
      query:
        type: string
        description: Search keywords