apiVersion: v1
kind: ReplicationController
metadata:
  name: search-api-rc
  labels:
    app: search-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: search-api
    spec:
      containers:
      - name: api
        image: "gcr.io/first-footing-108508/search-api"
        env:
        - name: API_KEYS
          value: '{"12345": "test-user"}'
        ports:
        - containerPort: 8080
