apiVersion: v1
kind: Service
metadata:
  name: search-api-svc
  labels:
    app: search-api
spec:
  ports:
    -
      port: 8080
      targetPort: 8080
  selector:
    app: search-api
  type: NodePort
